### ISSUE TITLE
curses-gui crashes 

### ISSUE THREAD

**Issue by xherbie** [jheled/royalur#2]
Occured while trying to put a stone out of the board (i.e. Position 8 and dice value 4)

loading database...,
done.
Traceback (most recent call last):
  File "./bin/curses-gui", line 375, in <module>
    curses.wrapper(ut_interface)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "./bin/curses-gui", line 326, in ut_interface
    assert validBoard(board),str(board)
AssertionError: [-1, 1, 1, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0, 1, -1, 0, 0, -1, 0, 0, 0]

**Comment by jheled** [comment]
Thank you (x)Herbie.

I strongly suggest you try tkur, the GUI version, which offers a far nicer user experience. 
I don't think I will have the time (or inclination) to fix bugs in this experimental curses interface.

-Joseph
